### ISSUE TITLE
G4NRFPhysics.cc error 34:3 'aParticleIterator' not declared in this scope

### ISSUE THREAD

**Issue by yacubus-bishcus** [jvavrek/NIMB2018#2]
When attempting to incorporate G4NRFPhysics.cc into my own code I Get the following error: 
aParticleIterator->reset(); not declared in this scope 
suggested alternative: 'GetParticleIterator'
GetParticleIterator->reset();

**Comment by yacubus-bishcus** [comment]
Ah I found the issue by looking at your source code comment. Does G4NRFPhysics.cc work for Geant4 version 10.5?

**Comment by jvavrek** [comment]
If I recall, the check
```
// Check if Geant4 version is >= 10.3.0
#if G4MAJV * 10000 + G4MINV * 100 + G4SUBV > 100299
auto aParticleIterator=GetParticleIterator();
#endif
```
worked well for us switching across the 10.3 boundary on different machines. It expect it should with 10.5, but if not, please let me know.

**Comment by jvavrek** [comment]
@jacobbickus I was able to clone the repo onto a fresh laptop with a geant4.10.5 install and get it up and running with no compiler errors. There was a small visualization issue that I solved by changing `OGLIX` to `OGLSX` in one of the vis scripts, though I don't know if that's a geant4 version issue per se. Let me know if you run into any other issues; if not, I'll close this Friday.

**Comment by yacubus-bishcus** [comment]
I was able to get it up and running without issue after I commented out the
if statement checking for Geant4 10.3 in NRF.cc.
Thanks for the quick responses!

Very Respectfully,
Jacob E Bickus
2LT, US Army
Lincoln Laboratory Military Fellow
MIT, Graduate Student
Cell: 412-849-6898

**Comment by jvavrek** [comment]
Sounds good; I'll close this
